### ISSUE TITLE
error compiling driver

### ISSUE THREAD

**Issue by kylerbrown** [melizalab/jack_rhd2000#3]
scons complains about missing `driver.h`.

```
kjbrown@sonoftweet:~/src/jack_rhd2000$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o driver/jack_rhd2k_driver.os -c -DSERVER_SIDE -fpermissive -Wall -g2 -fPIC -Ilib -Ijack -Ijack/include -Ijack/config driver/jack_rhd2k_driver.cpp
driver/jack_rhd2k_driver.cpp:41:20: fatal error: driver.h: No such file or directory
compilation terminated.
scons: *** [driver/jack_rhd2k_driver.os] Error 1
scons: building terminated because of errors.
```

**Comment by dmeliza** [comment]
I'm pushing a patch to the README that explains how to fix this. It involves downloading the JACK source code so that you get access to the headers used by the engine. Please give this a try and then close the issue if it works. I was only able to get the procedure to work with the most recent version of JACK, 0.124. YMMV with earlier versions - you may have to dig out those headers by hand.

Note that I have NOT done any testing with JACK versions later than 0.122, so I strongly recommend doing some stress testing before collecting important data.

**Comment by kylerbrown** [comment]
Worked! I did need to `sudo apt-get install uuid-dev` for uuid.h in Debian.
